<a href="https://colab.research.google.com/github/NehaDINNOV/CareerCounsellingApp/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [2]:
import numpy as np

Numpy Array using python structure

In [3]:
import numpy as np

In [4]:
myarr = np.array([[3,6,32,7,8],[4,5,6,8,7]],np.int32)

In [5]:
myarr

array([[ 3,  6, 32,  7,  8],
       [ 4,  5,  6,  8,  7]], dtype=int32)

In [6]:
a= myarr +2
a

array([[ 5,  8, 34,  9, 10],
       [ 6,  7,  8, 10,  9]], dtype=int32)

In [7]:
myarr

array([[ 3,  6, 32,  7,  8],
       [ 4,  5,  6,  8,  7]], dtype=int32)

In [8]:
myarr.shape

(2, 5)

In [9]:
myarr.dtype

dtype('int32')

In [10]:
zeros=np.zeros((3,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
range= np.arange(16)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
line_spacing = np.linspace(1,50,50)
line_spacing

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [14]:
import numpy as np
emp =np.empty((3,4))

In [15]:
emp

array([[1.04812973e-315, 0.00000000e+000, 2.10077583e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.35541533e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.46151512e-312,
        2.41907520e-312]])

In [16]:
emp_like =np.empty_like(emp)

In [17]:
emp_like

array([[1.04812973e-315, 0.00000000e+000, 2.10077583e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.35541533e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.46151512e-312,
        2.41907520e-312]])

In [18]:
ide =np.identity(5)

In [19]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
ide.shape

(5, 5)

In [21]:
arr=np.arange(99)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr= arr.reshape(9,11)

In [24]:
arr=arr.ravel()
arr.shape

(99,)

In [25]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [26]:
ar=np.array(x)

In [27]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [28]:
ar.sum(axis=0)

array([12,  8,  9])

In [29]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [30]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [31]:
ar.flat

In [32]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [33]:
ar.ndim

2

In [34]:
ar.size

9

In [35]:
ar.nbytes

72

In [36]:
one = np.array([12,2,568,1])

In [37]:
one.argmin()

np.int64(3)

In [38]:
one.argmax()

np.int64(2)

In [39]:
ar.argmin()

np.int64(8)

In [40]:
ar.argmax()

np.int64(6)

In [41]:
ar.argmax(axis=0)

array([2, 1, 1])

In [42]:
ar.argmax(axis=1)

array([2, 2, 0])

In [43]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [46]:
ar.ravel

<function ndarray.ravel>

In [47]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar2 =np.array([[1,2,1],[4,0,6],[8,1,0]])

In [49]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [50]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [51]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [52]:
ar.min()

np.int64(0)

In [53]:
ar.max()

np.int64(7)

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [56]:
np.count_nonzero(ar)

8

In [57]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [58]:
ar[0,0]=2

In [59]:
import sys

In [60]:
py_ar=[0,4,55,2]
np_ar=np.array(py_ar)

In [61]:
sys.getsizeof(1)*len(py_ar)

112

In [62]:
np_ar.itemsize*np_ar.size

32

In [63]:
np_ar.tolist()

[0, 4, 55, 2]

In [64]:
full= np.full((2,2),7)

In [65]:
ar.strides

(24, 8)

In [66]:
ar.data

In [67]:
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [68]:
ar.flat